apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: item-service
        image: ninjadoc/demo-ms-app-item-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
        - name: DB_HOST
          value: item-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: itemdb
---
apiVersion: v1
kind: Service
metadata:
  name: item-service
spec:
  selector:
    app: item-service
  ports:
  - port: 8082
    targetPort: 8082 