apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: ninjadoc/demo-ms-app-order-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
        env:
        - name: DB_HOST
          value: order-db
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: postgres
        - name: DB_PASSWORD
          value: postgres
        - name: DB_NAME
          value: orderdb
        - name: USER_SERVICE_URL
          value: "http://user-service:8081"
        - name: ITEM_SERVICE_URL
          value: "http://item-service:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 8083
    targetPort: 8083 